//
//  NCMessageCellNotificationModel.m
//  NexconnChatUI
//
//  Created by nexconn-ios on 10/4/26.
//  Copyright (c) 2026 Nexconn. All rights reserved.
//

#import "NCMessageCellNotificationModel.h"

NSString *const CONVERSATION_CELL_STATUS_SEND_BEGIN = @"CONVERSATION_CELL_STATUS_SEND_BEGIN";
NSString *const CONVERSATION_CELL_STATUS_SEND_FAILED = @"CONVERSATION_CELL_STATUS_SEND_FAILED";
NSString *const CONVERSATION_CELL_STATUS_SEND_CANCELED = @"CONVERSATION_CELL_STATUS_SEND_CANCELED";
NSString *const CONVERSATION_CELL_STATUS_SEND_SUCCESS = @"CONVERSATION_CELL_STATUS_SEND_SUCCESS";
NSString *const CONVERSATION_CELL_STATUS_SEND_PROGRESS = @"CONVERSATION_CELL_STATUS_SEND_PROGRESS";
NSString *const CONVERSATION_CELL_DATA_IMAGE_KEY_UPDATE =
    @"CONVERSATION_CELL_DATA_IMAGE_KEY_UPDATE";
NSString *const CONVERSATION_CELL_STATUS_SEND_READ_RECEIPT_INFO =
    @"CONVERSATION_CELL_STATUS_SEND_READ_RECEIPT_INFO"; // Read receipt information.

@implementation NCMessageCellNotificationModel

@end
